backend:
  name: github
  repo: catskald/legendary-creatures
  branch: master
  site_domain: https://catskald.github.io/

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "assets/img"
show_preview_links: true
slug:
  encoding: "unicode"
  clean_accents: true

collections:
  - name: "creatures-en"
    label: "Creatures (English)"
    label_singular: "Creature (English)"
    folder: "creatures"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "en.md"
    format: frontmatter
    #identifier_field: name TODO
    fields:
      - {
          label: "Name",
          hint: "The most common name of the creature.",
          name: "title",
          widget: "string",
        }
      - {
          label: "Plural name",
          hint: "The plural form of the name.",
          name: "plural",
          widget: "string",
        }
      - {
          label: "Other names",
          hint: "Names in the languages of origin, variations of the name, alternative names.",
          name: "names",
          widget: "list",
          required: false,
        }
      - {
          label: "Short description",
          hint: "One sentence briefly describing the creature.",
          name: "description",
          widget: "string",
        }
      - {
          label: "Folklore",
          hint: "A folklore the creature belongs to.",
          name: "folklore",
          widget: "list",
        }
      - {
          label: "Categories",
          hint: "Categories that describe the creature. Please enter as many as you see fit.",
          name: "categories",
          widget: "list",
        }
      - {
          label: "Origin",
          hint: "One or more countries or regions where the creature is originating from.",
          name: "origin",
          widget: "list",
          required: false,
        }
      - {
          label: "Origin",
          hint: "Please mark the area of the creature origin. Due to technical limitations it's possible to select single area only.",
          name: "map",
          widget: "map",
          required: false,
          decimals: 2,
          type: "Polygon",
        }
      - {
          label: "Related creatures",
          hint: "Other creatures that has any relations to the given creature.",
          name: "related",
          collection: "creatures-en",
          searchFields:
            [
              "name",
              "names",
              "origin",
              "folklore",
              "categories",
              "areal",
            ],
          valueField: "name",
          multiple: true,
          widget: "relation",
          required: false,
          optionsLength: 10,
        }
      - {
          label: "Number",
          hint: "According to beliefs, was it a single unique creature, a rare species or a common wide-spread kind?",
          name: "number",
          widget: "select",
          required: false,
          options: ["common", "rare", "unique"],
        }
      - {
          label: "Habitat",
          hint: "The type of environment in which the creature usually lives.",
          name: "habitat",
          widget: "list",
          required: false,
        }
      - {
          label: "image",
          hint: "An optional image of the creature.",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "Wikipedia link",
          hint: "An optional link to the Wikipedia article about the creature.",
          name: "wikipedia",
          widget: "string",
          required: false,
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "creatures-ru"
    label: "Creatures (Russian)"
    label_singular: "Creature (Russian)"
    folder: "creatures"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "ru.md"
    format: frontmatter
    #identifier_field: name TODO
    fields:
      - {
          label: "Name",
          hint: "The most common name of the creature.",
          name: "title",
          widget: "string",
        }
      - {
          label: "Other names",
          hint: "Names in the languages of origin, variations of the name, alternative names.",
          name: "names",
          widget: "list",
          required: false,
        }
      - {
          label: "Short description",
          hint: "One sentence briefly describing the creature.",
          name: "description",
          widget: "string",
        }
      - {
          label: "Folklore",
          hint: "A folklore the creature belongs to.",
          name: "folklore",
          widget: "list",
        }
      - {
          label: "Categories",
          hint: "Categories that describe the creature. Please enter as many as you see fit.",
          name: "categories",
          widget: "list",
        }
      - {
          label: "Origin",
          hint: "One or more countries or regions where the creature is originating from.",
          name: "origin",
          widget: "list",
          required: false,
        }
      - {
          label: "Origin",
          hint: "Please mark the area of the creature origin. Due to technical limitations it's possible to select single area only.",
          name: "map",
          widget: "map",
          required: false,
          decimals: 2,
          type: "Polygon",
        }
      - {
          label: "Related creatures",
          hint: "Other creatures that has any relations to the given creature.",
          name: "related",
          collection: "creatures-ru",
          searchFields:
            [
              "name",
              "names",
              "origin",
              "folklore",
              "categories",
              "areal",
            ],
          valueField: "name",
          multiple: true,
          widget: "relation",
          required: false,
          optionsLength: 10,
        }
      - {
          label: "Number",
          hint: "According to beliefs, was it a single unique creature, a rare species or a common wide-spread kind?",
          name: "number",
          widget: "select",
          required: false,
          options: ["common", "rare", "unique"],
        }
      - {
          label: "Habitat",
          hint: "The type of environment in which the creature usually lives.",
          name: "habitat",
          required: false,
          widget: "list",
        }
      - {
          label: "image",
          hint: "An optional image of the creature.",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "Wikipedia link",
          hint: "An optional link to the Wikipedia article about the creature.",
          name: "wikipedia",
          widget: "string",
          required: false,
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "pages-en"
    label: "Pages (English)"
    label_singular: "Page (English)"
    folder: "pages"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "en.md"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - {
          label: "isPage",
          name: "page",
          widget: "hidden",
          default: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages-ru"
    label: "Pages (Russian)"
    label_singular: "Page (Russian)"
    folder: "pages"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "ru.md"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - {
          label: "isPage",
          name: "page",
          widget: "hidden",
          default: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
