---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: creatures
  label: Creatures (English)
  create: documents
  match: "*.en.md"
  new_doc_ext: en.md
  templates:
  - creature-en
- type: directory
  path: creatures
  label: Creatures (Russian)
  create: documents
  match: "*.ru.md"
  new_doc_ext: ru.md
  templates:
  - creature-ru
- type: directory
  path: creatures
  label: Creatures (Ukrainian)
  create: documents
  match: "*.uk.md"
  new_doc_ext: uk.md
  templates:
  - creature-uk
upload_dir: static/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ENV=staging
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
